name = "nahj-institute"
compatibility_date = "2024-01-01"

[assets]
directory = "dist"

routes = [
  { pattern = "nahjinstitute.com", custom_domain = true },
  { pattern = "www.nahjinstitute.com", custom_domain = true },
  { pattern = "journal.nahjinstitute.com", custom_domain = true }
]